default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres0
  username: postgres

development:
  <<: *default
  database: docker-rails-test_development

test:
  <<: *default
  database: docker-rails-test_test

production:
  <<: *default
  database: docker-rails-test_production
  username: docker-rails-test
  password: <%= ENV['DOCKER-RAILS-TEST_DATABASE_PASSWORD'] %>
